// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9rbPB3JmRLRFxgUuKTlWeAY1QWZxyZg',
    appId: '1:67511071949:web:59d123d6c5626d1d89a584',
    messagingSenderId: '67511071949',
    projectId: 'fir-quiz-b3694',
    authDomain: 'fir-quiz-b3694.firebaseapp.com',
    storageBucket: 'fir-quiz-b3694.firebasestorage.app',
    measurementId: 'G-C03T1E7HXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnNc7MsxuXwjYaE_8s5rQj1oshPrTCyvk',
    appId: '1:67511071949:android:a7c8b3fc00fcc80789a584',
    messagingSenderId: '67511071949',
    projectId: 'fir-quiz-b3694',
    storageBucket: 'fir-quiz-b3694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnd992MW79rCRvQGrG5HHqPgy1eua8pp8',
    appId: '1:67511071949:ios:ad81c07efa250a6c89a584',
    messagingSenderId: '67511071949',
    projectId: 'fir-quiz-b3694',
    storageBucket: 'fir-quiz-b3694.firebasestorage.app',
    iosBundleId: 'com.example.firebaseQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnd992MW79rCRvQGrG5HHqPgy1eua8pp8',
    appId: '1:67511071949:ios:ad81c07efa250a6c89a584',
    messagingSenderId: '67511071949',
    projectId: 'fir-quiz-b3694',
    storageBucket: 'fir-quiz-b3694.firebasestorage.app',
    iosBundleId: 'com.example.firebaseQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-9rbPB3JmRLRFxgUuKTlWeAY1QWZxyZg',
    appId: '1:67511071949:web:274a5e5991998d9f89a584',
    messagingSenderId: '67511071949',
    projectId: 'fir-quiz-b3694',
    authDomain: 'fir-quiz-b3694.firebaseapp.com',
    storageBucket: 'fir-quiz-b3694.firebasestorage.app',
    measurementId: 'G-5307LX1DX6',
  );
}
